// Generated by tools/sync-gen.mjs from index.html. Do not edit.
// @gen-start
const N=7, BOTTOMS=['areia','coral','pedra','alga'];
function seedFrom(s){let h=1779033703^s.length;for(let i=0;i<s.length;i++){h=Math.imul(h^s.charCodeAt(i),3432918353);h=h<<13|h>>>19}h=Math.imul(h^h>>>16,2246822507);h=Math.imul(h^h>>>13,3266489909);return (h^h>>>16)>>>0}
function mulberry(a){return function(){a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
const key=(r,c)=>r*100+c;
const combo=x=>x.b*4+x.d*2+x.l;
const bites=(x,f)=>(x.b===f.b)+(x.d===f.d)+(x.l===f.l);
const stars=n=>n<=2?3:n===3?2:1;
// The beach runs along the bottom edge: a square is shallow from its column's shelf row down to the shore.
// Shade is the shadow of two clouds, a square's centre inside an ellipse.
function genSea(date){
  for(let tries=1;;tries++){
    const rng=mulberry(seedFrom(`${date}:pista${tries>1?':'+tries:''}`)), ri=n=>Math.floor(rng()*n);
    const shelf=[];let sh=3+ri(3);for(let c=0;c<N;c++){shelf.push(sh);sh=Math.min(5,Math.max(3,sh+ri(3)-1))}
    const clouds=Array.from({length:2},()=>({r:rng()*N,c:rng()*N,rr:1.2+rng()*1.3,rc:1.5+rng()*1.5}));
    const pts=Array.from({length:6},(_,i)=>({r:rng()*N,c:rng()*N,b:i<4?i:ri(4)}));
    const grid=[];
    for(let r=0;r<N;r++){grid.push([]);for(let c=0;c<N;c++){
      let b=0,bd=1e9;for(const p of pts){const q=(p.r-r-.5)**2+(p.c-c-.5)**2;if(q<bd){bd=q;b=p.b}}
      const l=clouds.some(k=>((r+.5-k.r)/k.rr)**2+((c+.5-k.c)/k.rc)**2<=1)?1:0;
      grid[r].push({b,d:r>=shelf[c]?0:1,l});
    }}
    const present=[...new Set(grid.flat().map(combo))].sort((x,y)=>x-y);
    if(present.length===12){const f=present[ri(12)];return {grid,shelf,clouds,fish:{b:f>>2,d:(f>>1)&1,l:f&1},present,tries}}
  }
}
const SHAPES={
  oval:["......aaaaa.....","....aaaaaaaaa.ff","..aaaaaaaaaaaaff",".aweaaaaaaaaafff","aaaaaaaaaaaaafff",".acccccccccaaaff","..ccccccccccaaff","....cccccca...ff","......ff........"],
  tall:["......ff......",".....fff......","....aaaa......","...aaaaaa.....","..aaaaaaaa..ff",".aweaaaaaaaaff","aaaaaaaaaaaaff",".aaaaaaaaaaaff","..cccccccc..ff","...cccccc.....","....cccc......",".....fff......","......ff......"],
  round:[".....aaaa.....","...aaaaaaaa...","..aaaaaaaaaa.f",".aweaaaaaaaaff","aaaaaaaaaaaaaf","aaaaaaaaaaaaff",".acccccccccaaf","..cccccccccc..","...cccccccc...",".....cccc....."],
  flat:["....aaaaaaaa....","..aaaaaaaaaaaa..",".aaewaaaaaaaaaff","aaaaaaaaaaaaaaff",".aaewaaaaaaaaaff","..aaaaaaaaaaaa..","....aaaaaaaa...."],
  long:["...aaaaaaaaaa.f.",".awaaaaaaaaaaaff","aeaaaaaaaaaaaaff",".acccccccccccaff","...cccccccccc.f."],
  seahorse:["...aaa...","..aaaaf..",".aewaaf..","aaa.aa...","....aaa..","...aaaaf.","...acaaf.","...acaa..","...acaa..","....aaa..",".....aa..","...a.aa..","...aa.a..","....aa..."],
  ray:[".......aa.......","......aaaa......",".....aaaaaa.....","a...aaaaaaaa...a","aaaaaaaaaaaaaaaa",".aaaaawaawaaaaa.","..aaaaeaaeaaaa..","...aaaaaaaaaa...",".....aaaaaa.....",".......ff.......",".......ff.......","........f......."],
};
// rare: 1 uncommon, 2 rare (Saturdays only). Species is flavour and collection; it never changes the habits.
const SPECIES=[
  {id:'dourado',shape:'oval',pal:{a:'#F2C84B',b:'#C9962E',c:'#FFE9A0',f:'#E0A030'},spots:[[2,6],[4,9]]},
  {id:'palhaco',shape:'oval',pal:{a:'#F28A30',b:'#FFFFFF',c:'#F9A850',f:'#1A1A1A'},stripes:[3,8,12]},
  {id:'cirurgiao',shape:'oval',pal:{a:'#3E6FD8',b:'#14285A',c:'#2F58B8',f:'#F2C84B'},spots:[[2,6],[2,7],[2,8],[3,9],[3,10]]},
  {id:'garoupa',shape:'oval',pal:{a:'#A0744A',b:'#5E3A1A',c:'#C9A070',f:'#7A5230'},spots:[[2,5],[3,9],[4,3],[5,7],[2,11],[4,12]]},
  {id:'baiacu',shape:'round',pal:{a:'#D9B460',b:'#6B4A2A',c:'#F4E6BE',f:'#C79A40'},spots:[[1,5],[2,8],[3,11],[4,6],[2,3]]},
  {id:'papagaio',shape:'oval',pal:{a:'#3FBF8F',b:'#F2A0C8',c:'#7FE0B8',f:'#2E8F6A'},stripes:[5,10]},
  {id:'linguado',shape:'flat',pal:{a:'#C9A56A',b:'#8A6A40',f:'#A8844E'},spots:[[1,6],[3,9],[5,4],[5,11],[1,12]]},
  {id:'sardinha',shape:'long',pal:{a:'#8FB8D8',b:'#4E7FA8',c:'#E4EEF4',f:'#6E98BA'},spots:[[0,4],[0,6],[0,8]]},
  {id:'anjo',shape:'tall',rare:1,pal:{a:'#F2D24B',b:'#1A1A2A',c:'#FFE88A',f:'#3E6FD8'},stripes:[5,9]},
  {id:'cavalo',shape:'seahorse',rare:1,pal:{a:'#F28A30',b:'#B24E22',c:'#FFC07A',f:'#FFD08A'},spots:[[4,5],[9,5]]},
  {id:'leao',shape:'tall',rare:2,pal:{a:'#D8553A',b:'#FFFFFF',c:'#F4D8C8',f:'#E89080'},stripes:[3,6,9]},
  {id:'manta',shape:'ray',rare:2,pal:{a:'#2A4A7A',b:'#1A2E50',f:'#2A4A7A'},spots:[[3,7],[3,8],[4,3],[4,12]]},
];
function speciesMap(s){
  const m=SHAPES[s.shape].map(r=>[...r]);
  for(const c of s.stripes||[])for(const row of m)if(/[ac]/.test(row[c]||''))row[c]='b';
  for(const[r,c]of s.spots||[])if(/[ac]/.test(m[r]?.[c]||''))m[r][c]='b';
  return m.map(r=>r.join(''));
}
// Weekdays and Sunday draw from a per-week shuffle of the ten common species, so a week never repeats; Saturday is rare.
function speciesOf(date){
  const d=new Date(date+'T12:00:00'), wd=(d.getDay()+6)%7, mon=new Date(d); mon.setDate(d.getDate()-wd);
  const rare=SPECIES.filter(x=>x.rare===2), pool=SPECIES.filter(x=>x.rare!==2).map(x=>x.id);
  if(wd===5) return rare[Math.round(mon.getTime()/6048e5)%rare.length].id;
  const rng=mulberry(seedFrom(`${mon.getFullYear()}-${mon.getMonth()+1}-${mon.getDate()}:especie`));
  for(let i=pool.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]]}
  return pool[wd<5?wd:5];
}

export { N, genSea, bites, combo };
