// Copies art/*/*.png into index.html between // @art-start and // @art-end as data URLs, so the page stays one offline
// file. Also derives what the page needs and nobody draws: the greyed star and the dark silhouettes of unseen fish.
// Run `node tools/art-embed.mjs` after any change in art/; pista-check fails while the embedded copy is stale.
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { decodePNG, encodePNG } from './png.mjs';

const root = new URL('../', import.meta.url), GROUPS = ['fish', 'portrait', 'plate', 'guests', 'ui'];
const url = buf => `data:image/png;base64,${buf.toString('base64')}`;
const recolour = (buf, fn) => { const { w, h, rgba } = decodePNG(buf); for (let i = 0; i < rgba.length; i += 4) if (rgba[i + 3]) rgba.set(fn(rgba[i], rgba[i + 1], rgba[i + 2]), i); return encodePNG(w, h, rgba); };

export function artBlock() {
  const art = {};
  for (const g of GROUPS) {
    const dir = new URL(`art/${g}/`, root);
    if (!existsSync(dir)) continue;
    for (const f of readdirSync(dir).filter(f => f.endsWith('.png')).sort()) {
      const buf = readFileSync(new URL(f, dir)), key = `${g}/${f.slice(0, -4)}`;
      art[key] = url(buf);
      if (g === 'fish' || g === 'portrait') art[`${key}:dark`] = url(recolour(buf, () => [0x1E, 0x4A, 0x5A]));
      if (key === 'ui/star') art['ui/starOff'] = url(recolour(buf, (r, g2, b) => { const y = (r * .3 + g2 * .59 + b * .11) * .55 + 70; return [y + 8, y + 2, y - 14]; }));
    }
  }
  return `// @art-start\n// Generated by tools/art-embed.mjs from art/. Do not edit.\nconst ART=${JSON.stringify(art)};\n// @art-end`;
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split('/').pop())) {
  const file = new URL('index.html', root), html = readFileSync(file, 'utf8');
  const a = html.indexOf('// @art-start'), b = html.indexOf('// @art-end');
  if (a < 0 || b < a) throw new Error('@art markers not found in index.html');
  const block = artBlock();
  writeFileSync(file, html.slice(0, a) + block + html.slice(b + '// @art-end'.length));
  console.log(`art embedded: ${(block.match(/"[a-z]+\/[^"]+":/g) || []).length} images, ${Math.round(block.length / 1024)} KB`);
}
