// Copies the page's @gen block into the API so the server rebuilds each sea with the exact code players run.
import { readFileSync, writeFileSync } from 'node:fs';
const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const a = html.indexOf('// @gen-start'), b = html.indexOf('// @gen-end');
if (a < 0 || b < a) throw new Error('@gen markers not found');
export const genModule = `// Generated by tools/sync-gen.mjs from index.html. Do not edit.\n${html.slice(a, b)}\nexport { N, genSea, bites, combo };\n`;
if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split('/').pop())) {
  writeFileSync(new URL('../api/src/gen.js', import.meta.url), genModule);
  console.log('api/src/gen.js written');
}
